// examples/nuxt-example/app.vue
<template>
  <main class="nuxt-shell">
    <h1>Nuxt Demo</h1>
    <p>Use the hotkey and click this Nuxt page.</p>
    <button type="button" @click="count += 1">Clicked {{ count }} times</button>
  </main>
</template>

<script setup lang="ts">
const count = ref(0);
</script>

<style scoped>
.nuxt-shell {
  display: grid;
  gap: 12px;
  padding: 24px;
}
</style>

// examples/svelte-example/src/App.svelte
<script>
  let count = 0;
</script>

<main class="app-shell">
  <h1>Svelte Smoke Test</h1>
  <p>Hold the configured hotkey and click this paragraph to jump to App.svelte.</p>
  <button type="button" on:click={() => count += 1}>Clicked {count} times</button>
</main>

<style>
  .app-shell {
    font-family: sans-serif;
    display: grid;
    gap: 12px;
    padding: 24px;
  }
</style>
