// examples/vue-example/src/App.vue
<template>
  <main class="app-shell">
    <h1>Vue Smoke Test</h1>
    <p>Hold the configured hotkey and click this paragraph to jump to App.vue.</p>
    <button type="button" @click="count += 1">Clicked {{ count }} times</button>
  </main>
</template>

<script setup lang="ts">
import { ref } from "vue";

const count = ref(0);
</script>

<style scoped>
.app-shell {
  font-family: sans-serif;
  display: grid;
  gap: 12px;
  padding: 24px;
}
</style>

// examples/angular-example/src/app/app.component.ts
import { Component, signal } from "@angular/core";

@Component({
  selector: "app-root",
  standalone: true,
  templateUrl: "./app.component.html",
  styleUrl: "./app.component.css",
})
export class AppComponent {
  readonly count = signal(0);

  increment(): void {
    this.count.update((value) => value + 1);
  }
}
<main class="app-shell">
  <h1>Angular Smoke Test</h1>
  <p>Hold the configured hotkey and click this paragraph to jump to app.component.html.</p>
  <button type="button" (click)="increment()">Clicked {{ count() }} times</button>
</main>
